---
name: Lchown
version: 1.01
author:
  - 'Nick Cleaton <nick@cleaton.net>'
abstract: use the lchown(2) system call from Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Lchown:
    file: lib/Lchown.pm
    version: 1.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
